### Basic python

In [32]:
L=[2, 3, 4, 2, 1, 2, 3]
print(L.index(2))
# ans-->> 0

0


In [35]:
L = [2, 1, 2, 4, 5, 3, 6]
K = 4 in L
print(K)

True


In [42]:
# How will you add the list A = [10, 20, 30] at the end of list 
# B = [45, 35, 25], making the final list as [45, 35, 25, 10, 20, 30].
B = [45, 35, 25]
A = [10, 20, 30]
B.extend(A) # answer
B


[45, 35, 25, 10, 20, 30]

In [ ]:

# You have to find and print the smallest element of the list given as input. 

import ast
input_str = input()
input_list = ast.literal_eval(input_str)
print(min(input_list))

In [52]:
# # You are planning to go to your friend's wedding and you have long events all month, 
# # lasting at least a few days. You have the start and end dates of events and 
# # your task is to find out events overlapping with the wedding date.

import ast
input_str1 = input()
input_list1 = ast.literal_eval(input_str1)
events = input_list1

wedding = int(input())

clash=0
for i in events:
    if wedding in range(i[0],i[1]+1):
        clash+=1
print(clash)

### Adv python

In [74]:
# Character
# What will be the output of the following?

(print(chr(51)))
# ans -> 3

3


In [62]:
# Given an ASCII code, 
# how will you find the character associated with it? 
# Suppose the given ASCII code is 123.
print(chr(123))

{


In [64]:
# Strip
# What does the following line of code do to a string S

S=' hey '
S.strip()
print(S)

 hey 


In [65]:
sentence='python is super easy and fun'
for i in sentence.split()[::-1]:
    print(i,end=' ')

fun and easy super is python 

In [73]:
# You will be given two strings. 
# You have to find the largest prefix common in both the strings.

string1=input().lower()
string2=input().lower()
common=0
for i in range(min(len(string1),len(string2))):
    if string1[i]==string2[i]:
        common+=1
    else:
        break
if common>0:
    print(string1[:common])
else:
    print(-1)

upgrad


### Data Stuctures

In [ ]:
# Basic Stack Operations
# Which of the following operations cannot be performed when the stack is already full?

# ans -> push

In [ ]:
# ans -->
# The stack will be empty. However, there is a closing parenthesis left in the string that 
# does not have a corresponding opening parenthesis. Therefore,
# there is nothing to pop, and the algorithm will return 'false'.

In [75]:
# Given a string, reverse it using a stack and print it.


def check_palindrome(string,s):
  # write your logic here
  return(string[::-1])

'yeh'

In [ ]:
# Note: If the number of elements in the queue is less than k, 
# then print “There are not enough elements in the queue”.




def print_element(q,k):
    # q- input queue, k- kth element from the front
    # print the kth element from the front end of queue
    # write your code here. 
    if q.size()<k:
        print ("There are not enough elements in the queue")
    else:
        elm=q.size()-k
        for i in range(elm+1):
            a=q.dequeue()
        print(a)

### Search

In [ ]:
# Linear Search vs Binary Search
# In the binary search algorithm, after every search operation, the search gets reduced by ______?
# ans -> 1/2


In [ ]:
# Divide and Conquer
# The step(s) in the divide and conquer process that 
# initiate(s) a recursive approach is/are said to be

# divide

In [ ]:
# Choose whether the following statement is True or False:
# Since you know that binary search is more efficient than linear search, 
# and since the binary search can be applied only on a sorted array, 
# the most efficient way to approach this task is to first sort the array and then apply binary search.

# ans -> False

In [99]:
# Binary Search
import ast
sorted_list=ast.literal_eval(input())
key=int(input())

pointer=-1
for i in range(len(sorted_list)):
    if sorted_list[i]==key:
        pointer=i
        break
if pointer>=0:
    print(pointer)
else:
    print(pointer)

In [ ]:
# Rotated List

import ast
sorted_list=ast.literal_eval(input())
key=int(input())

pointer=-1
for i in range(len(sorted_list)):
    if sorted_list[i]==key:
        pointer=i
        break
if pointer>=0:
    print(pointer)
else:
    print(pointer)

### Sorting

In [ ]:
# In-Place Sorting Algorithms

# ans-> All of the above

In [ ]:
# 2nd

# a) If there are N items, then Bubble sort performs exactly N*N comparisons



In [100]:
def func(x):
     return x % 10

L = [15, 20, 5, 29, 10]
sorted(L, key = func)
# ans-> [20, 10, 15, 5, 29]

[20, 10, 15, 5, 29]

In [105]:
# Using the Built-in Sort Function

import ast,sys
input_str = sys.stdin.read()
input_list = ast.literal_eval(input_str)
def func(x):
     return len(x)

print(sorted(input_list, key = func))


['I', 'to', 'in', 'love', 'code', 'Python']


In [106]:
# Custom Sort

import ast,sys
input_str = sys.stdin.read()
input_list = ast.literal_eval(input_str)
def func(x):
     return x % 5
print(sorted(input_list, key = func))

[5, 3, 2, 1]


### timed test-1

In [115]:
# Output: A list of tuples containing the first occurrence of the symmetric pair.

import ast
# input has been taken for you
l=ast.literal_eval(input())
a=[]
for i in range(len(l)-1):
    element=l[i]
    for j in range(i,len(l)):
        if element[0]==l[j][1] and element[1]==l[j][0]:
            a.append(element)
            break
print(a)

(40, 50)


In [129]:
# Sort in Increasing and Decreasing Order

l= ast.literal_eval(input())
odd=[]
even=[]
for i in range(len(l)):
    if i%2==0:
        even.append(l[i])
    else:
        odd.append(l[i])
even.sort()
odd.sort(reverse=True)
even.extend(odd)
print(even)

[3, 5, 6, 8, 7, 4]

### timed test-2

In [153]:
# Common Elements in All Rows of a Matrix

import ast
l=ast.literal_eval(input())
dic={}
if len(l)==1:
    output=l[0]
    output.sort()
    print(output)
elif len(l)==0:
    print([])
else:
    for j in range(len(l[0])):
        dic[l[0][j]]=1
        for i in range(1,len(l)):
            if l[0][j] in l[i]:
                dic[l[0][j]]+=1
            
    output=[key for key,value in dic.items() if value==len(l)]
    output.sort()
    print(output)
# write your code here

[2, 3]


In [155]:
# function to detect duplicate_paranthesis       
def duplicate_paranthesis(string):
  #write your logic here
	Stack = []
	for ch in string:
		if ch == ')':
			top = Stack.pop()
			elementsInside = 0
			while top != '(':
			
				elementsInside += 1
				top = Stack.pop()
			
			if elementsInside < 1:
				return True
		else:
			Stack.append(ch)
	
	return False
  
  

True
False
False
False


# **Python Lab-2**

### Part-1 **Numpy**

In [2]:
# Given m and n, swap the mth and nth columns of the 2-D NumPy array given below.

import numpy as np 
# Given array
a = np.array([[4, 3, 1], [5, 7, 0], [9, 9, 3], [8, 2, 4]])

# Read the values of m and n
import sys
# lines = sys.stdin.readlines()
m = int(lines[0])
n = int(lines[1])
a[:, [m, n]] = a[:, [n, m]]

print(a)

In [11]:
# Write the code to store the table of 13 ( first 10 multiples )in the first row of an array and
#  in the second-row store table of 15.

import numpy as np
array =np.array([np.arange(1,11)*13,np.arange(1,11)*15])

print(array)


array([[ 13,  26,  39,  52,  65,  78,  91, 104, 117, 130],
       [ 15,  30,  45,  60,  75,  90, 105, 120, 135, 150]])

In [20]:
# Border Rows and Columns
# Extract all the border rows and columns from a 2-D array.

import ast,sys
input_str = sys.stdin.read()
input_list = ast.literal_eval(input_str)

import numpy as np

# Convert the input list to a NumPy array
array_2d =np.array(input_list)

# Extract the first column, first row, last column and last row respectively using
# appropriate indexing
col_first = array_2d[:,0]
row_first = array_2d[0,:]
col_last = array_2d[:,-1]
row_last = array_2d[-1,:]
print(col_first)
print(row_first)
print(col_last)
print(row_last)

[11 21 31]
[11 12 13 14]
[14 24 34]
[31 32 33 34]


In [29]:
# Extracting Certain Elements
# From a given array, extract all the elements which are greater than or equal to 'm' and less than or equal to 'n'. 
# Note: 'm' and 'n' are integer values provided as input.

import ast 
input_list=ast.literal_eval(input())
m=int(input())
n=int(input())

import numpy as np
array_1 = np.array(input_list)
final_array = array_1[(array_1>=m) & (array_1<=n)]


print(final_array)



array([21])

### Part-2 **Pandas**

In [34]:
# Cube of a series
# Create a panda series that contains the first ‘n’ natural numbers and their respective cubes. 
# The first ‘n’ numbers should appear in the index position.

# Read the variable from STDIN
n = int(input())

import numpy as np 
import pandas as pd 
series=pd.Series(data=[i**3 for i in range(1,n+1)],index=range(1,n+1))
print(series)




1      1
2      8
3     27
4     64
5    125
dtype: int64


In [ ]:
# Question 2
# Training for Employees

import numpy as np
import pandas as pd

# The file is stored at the following path:
# 'https://media-doselect.s3.amazonaws.com/generic/NMgEjwkAEGGQZBoNYGr9Ld7w0/rating.csv'
df = pd.read_csv('https://media-doselect.s3.amazonaws.com/generic/NMgEjwkAEGGQZBoNYGr9Ld7w0/rating.csv')

# Provide your answer below
df['Training']=np.where(df['Rating']<=3 ,'Yes','No')
print(df.head())

In [ ]:
# Question 3
# Selecting Columns of a Dataframe 2


import pandas as pd
df = pd.read_csv('https://cdn.upgrad.com/uploads/production/b3467ba4-4e13-44e9-8087-4d7e94cc7586/forestfires.csv')
df_2 = df[['month', 'day' , 'wind' , 'rain']] 
print(df_2.head(20))

In [ ]:

# Question 4  
# Conditions in Dataframes
# upgrad solution -------------->>>
import pandas as pd
df = pd.read_csv('https://cdn.upgrad.com/uploads/production/b3467ba4-4e13-44e9-8087-4d7e94cc7586/forestfires.csv')
df_2 = df.loc[(df.month == 'aug')&(df.temp>10),:]
print(df_2.head(20))



# Graded

In [ ]:
# Question 1
# 1. Number of rows where price is not in INR

a=df.loc[(df.currency!='INR'),:].shape[0]

print(a)

In [ ]:
# Question 2
# 2. Dropping and renaming columns
df.drop(['currency'],inplace=True,axis=1)
df.rename(columns = {'price':'inrprice'}, inplace = True)
print(df.head())

In [3]:
# Question 3
# 3. List of items sold

import numpy as np 
a=[]
for i in df.commodity:
    if i not in a:
        a.append(i)
a=np.array(a)
print(a)

In [ ]:
# 4. Average price of rice

city=input()
# df.dropna(inplace=True)
price= df.loc[(df.unit=='KG') & (df.commodity=='Rice') & (df.market==city),:]['price']
a=[]
for i in price:
    a.append(float(i))
print(round(sum(a)/len(a),2))

In [ ]:
# Question-5

commodity = input()
df_7 = df[(df['commodity']==commodity)]
max_value = df_7['price'].apply(float).max()
print(df_7.loc[df['price']==max_value,'market'].to_string(index=False))